### ISSUE TITLE
Interested in adding this to Contentfuls samples repo?

### ISSUE THREAD

**Issue by floelhoeffel** [suhmantha1/contentful-ui-shopify#1]
Hey @suhmantha1 ,

Nice shopify UI Extensions! If you are interested, you could send a PR to our official samples repo so this extensions will be more discoverable? The only ask I would have is to add a license file with something like MIT.

https://github.com/contentful/extensions/tree/master/samples

Thanks,
Frederik

**Comment by suhmantha1** [comment]
@floelhoeffel Would love to see this extension more discoverable! Just submitted a PR to the repo

**Comment by floelhoeffel** [comment]
Fantastic - I ll get someone to review it - thanks!
